name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]

    steps:
      - name: Print current OS
        run: echo "Running on ${{ matrix.os }}"
